### PR TITLE
test with this mod for pnlf

### PR DESCRIPTION
**Pull request by Lorys89**

### CODE REVIEW

**Comment by Lorys89** [comment]
change ig platform id to 09009B3E

**Comment by hacker1024** [comment]
AAPL,ig-platform-id | Type | Comment
-- | -- | --
0900A53E | Laptop | Recommended value for UHD 630
00009B3E | Laptop | Recommended value for UHD 620

Do you mean 00009B3E?

**Comment by hacker1024** [comment]
It looks like you forgot to add a new SSDT-PNLF.aml after you deleted it. I'll try the latest DSL from your master branch.

**Comment by hacker1024** [comment]
Your latest version works, thanks!

**Pull request closed without merging**
